### ISSUE TITLE
QUESTION: Where do I have to put the accounts and how do I run the bot?

### ISSUE THREAD

**Issue by urkoperez16** [NFKRZZ/PlaceBot#1]

**Comment by NFKRZZ** [comment]
You have to put the accounts.txt where the executable is so with the current project settings that would be PlaceBot2.0\PlaceBot2.0\bin\Debug\net7.0-windows10.0.22621.0

**Comment by NFKRZZ** [comment]
Keep in mind you will need proxies if you don't want to get your accounts banned

**Comment by urkoperez16** [comment]
if i use tor expert bundle is okey?

**Comment by NFKRZZ** [comment]
This project does not support tor
