### ISSUE TITLE
How do I run the bot?

### ISSUE THREAD

**Issue by urkoperez16** [NFKRZZ/PlaceBot#2]
reply please, How do I enter the coordinates? im at windows

**Comment by urkoperez16** [comment]
reply please, How do I enter the coordinates? im at windows

**Comment by NFKRZZ** [comment]
![image](https://github.com/NFKRZZ/PlaceBot/assets/43969824/e505e7c0-36e8-43b8-a72e-ec34f3153270)
edit this for your coords

**Comment by NFKRZZ** [comment]
you need to open the solution in visual studio 2022 also.
